#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. "${WM_PROJECT_DIR:?}"/bin/tools/RunFunctions      # Tutorial run functions
#------------------------------------------------------------------------------
cp -r 0.orig 0
touch post.foam

# execute the meshing, assuming blockMeshDict was already written
runApplication blockMesh

# decompose and renumber
runApplication decomposePar
runParallel checkMesh -allGeometry -allTopology
runParallel renumberMesh -overwrite

# execute flow solver
runParallel "$(getApplication)"



