#!/bin/bash
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=100
#SBATCH --time=48:00:00
#SBATCH --job-name=buffet

module load development/24.04 GCC/12.3.0 
module load OpenMPI/4.1.5
module load OpenFOAM/v2312 
source $FOAM_BASH

# path to the test case (adjust if necessary)
cd "buffet_oat15/OAT15/"

./Allrun &> "log.main"

