#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. "${WM_PROJECT_DIR:?}"/bin/tools/RunFunctions      # Tutorial run functions
#------------------------------------------------------------------------------
cp -r 0.orig 0
touch post.foam

# execute the meshing, assuming blockMeshDict was already written
runApplication blockMesh

# refine the wake region so we have a proper DDES mesh
runApplication snappyHexMesh -overwrite

# clean up
rm constant/polyMesh/cellLevel constant/polyMesh/level0Edge constant/polyMesh/pointLevel 0/cellLevel 0/pointLevel

# parallel not working, order createPatch and extrusion also no effect -> if order different extrudeMesh fails (even with adjusted names)
runApplication createPatch -overwrite
runApplication extrudeMesh -noFunctionObjects

# decompose and check
runApplication decomposePar

runParallel checkMesh -allGeometry -allTopology # -writeAllFields 
runParallel renumberMesh -overwrite

# execute flow solver
runParallel "$(getApplication)"            # TODO: rhoPimpleFoam scotch not found error if createPatch is used, doesn't matter if serial or parallel

# compute the cell centers and volumes
runParallel postProcess -func "writeCellCentres" -constant -time none
mv log.postProcess log.postProcess.writeCellCentres
runParallel postProcess -func "writeCellVolumes" -constant -time none
mv log.postProcess log.postProcess.writeCellVolumes



